spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath*:/mapper/todo/*.xml
  configuration:
    map-underscore-to-camel-case: true
